COPY stg_network_connections (
    ts_raw,
    uid,
    id_orig_h,
    id_orig_p,
    id_resp_h,
    id_resp_p,
    proto,
    service,
    duration,
    orig_bytes,
    resp_bytes,
    conn_state,
    local_orig,
    local_resp,
    missed_bytes,
    history,
    orig_pkts,
    orig_ip_bytes,
    resp_pkts,
    resp_ip_bytes,
    tunnel_parents,
    label,
    detailed_label
) FROM STDIN WITH (FORMAT csv, HEADER true, DELIMITER '|');
